{{- if and .Values.metrics.enabled .Values.metrics.service.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fleet-management-operator.fullname" . }}-metrics-monitor
  labels:
    {{- include "fleet-management-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.service.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - path: /metrics
    port: http
    interval: {{ .Values.metrics.service.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.metrics.service.serviceMonitor.scrapeTimeout }}
  selector:
    matchLabels:
      {{- include "fleet-management-operator.selectorLabels" . | nindent 6 }}
{{- end }}
